import Head from "next/head";
import IndexPage from "@src/pages/main-index/index";

export default function Home({title}: any) {
  return (
    <>
      <Head>
        <title>Kalles - Clean, Versatile, Responsive Bootstrap 5 & Nextjs Theme</title>
        <meta name="description" content="Generated by Kalles" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <IndexPage />
      </main>
    </>
  );
}
