const ProductLayout = [
    { id: "ProductDetailLayout1", label: "Product Detail Layout 1", link: "/product-detail-layout-01" },
    { id: "ProductDetailLayout2", label: "Product Detail Layout 2", link: "/product-detail-layout-02" },
    { id: "ProductDetailLayout3", label: "Product Detail Layout 3", link: "/product-detail-layout-03" },
    { id: "Productthumbatbottom", label: "Product thumb at  bottom", link: "/product-detail-thumb-bottom" },
    { id: "Productthumbonright", label: "Product thumb on right", link: "/product-detail-thumb-right" },
    { id: "Productwithoutthumbnail", label: "Product without thumbnail", link: "/product-detail-without-thumbnail" },
    { id: "LeftSidebar", label: "Left Sidebar", link: "/product-detail-left-sidebar" },
    { id: "RightSidebar", label: "Right Sidebar", link: "/product-detail-right-sidebar" },
    { id: "SidebarFullHeight", label: "Sidebar Full Height", link: "/product-detail-sidebar-full-height" },
    { id: "ProductTabAccordions", label: "Product Tab Accordions", link: "/product-detail-tab-accordion" },
    { id: "ProductFullWidthATC", label: "Product Full Width ATC", link: "/product-detail-full-width-atc" },
    { id: "Productfullwidthlayout", label: "Product full width layout", link: "/product-detail-full-width" },
    { id: "AdvanceProductType", label: "Advance Product Type", link: "/product-detail-advance-product-type"},
]
const ProductDetail = [
    { id: "External/AffiliateProduct", label: "External/Affiliate Product", link: "/product-detail-external-affiliate" },
    { id: "Simpleproduct", label: "Simple product", link: "/product-detail-simple-product" },
    { id: "Variableproduct", label: "Variable product", link: "/product-detail-layout-01" },
    { id: "GroupedProduct", label: "Grouped Product", link: "/product-detail-grouped-product", badge: "Hot", badgeColor: "badge-tag badge bg-danger"},
    { id: "InnerZoom#1", label: "Inner Zoom #1", link: "/product-detail-layout-02" },
    { id: "ExternalZoom", label: "External Zoom", link: "/product-detail-layout-01" },
    { id: "InnerZoom#2", label: "Inner Zoom #2", link: "/product-detail-layout-03" },
    { id: "PhotoSwipePopup", label: "PhotoSwipe Popup", link: "/product-detail-layout-01" },
    { id: "Descriptionwithproduct", label: "Description with product", link: "/product-detail-description-with-product" },
    { id: "Descriptionwithinstagramshop", label: "Description with instagram shop", link: "/product-detail-description-with-instagram-shop" },
    { id: "Productvideo", label: "Product video", link: "/product-detail-product-video"},
    { id: "Product3DARmodels", label: "Product 3D, AR models", link: "/product-detail-3d-ar-models" },
]
const ProductSwatch = [
    { id: "ProductColorSwatch", label: "Product Color Swatch", link: "/product-detail-layout-01" },
    { id: "ProductGallerySwatch", label: "Product Gallery Swatch", link: "/product-detail-swatch-color" },
    { id: "ProductImages", label: "Product Images Swatch", link: "/product-detail-swatch-color" },
    { id: "SwatchColor", label: "Swatch Color", link: "/product-detail-swatch-color" },
    { id: "SwatchColorCircle", label: "Swatch Color Circle", link: "/product-detail-layout-01" },
    { id: "SwatchRadio", label: "Swatch Radio", link: "/product-detail-swatch-radio" },
    { id: "SwatchRadioColor", label: "Swatch Radio Color", link: "/product-detail-swatch-radio-color" },
    { id: "SwatchRectangle", label: "Swatch Rectangle", link: "/product-detail-swatch-rectangle" },
    { id: "SwatchRectangle Color", label: "Swatch Rectangle Color", link: "/product-detail-swatch-rectangle-color" },
    { id: "SwatchSimple", label: "Swatch Simple", link: "/product-detail-swatch-simple" },
    { id: "SwatchSimpleColor", label: "Swatch Simple Color", link: "/product-detail-swatch-simple-color" },
]
const ProductFeatures = [
    { id: "FrequentlyBoughtTogether", lable: "Frequently Bought Together", link: "/product-detail-frequently-bought-together", badge: "new", badge2: "Hot", badgeColor2: "badge-tag badge bg-danger", badgeColor: "badge-tag badge bg-teal", badgeStyle: { "whiteSpace": "nowrap" }, badstyle2: { "right": "-40px", "top": "2px" } },
    { id: "Productpre-orders", lable: "Product pre-orders", link: "/product-detail-pre-orders" },
    { id: "ProductUpsell", lable: "Product Upsell", link: "/product-detail-tab-accordion", badge: "Hot", badgeColor: "badge-tag badge bg-danger", badge2: "Hot", badgeColor2: "badge-tag badge bg-danger", },
    { id: "DescriptionwithLookbook", lable: "Description with Lookbook", link: "/product-detail-description-with-lookbook", badge: "Hot", badgeColor: "badge-tag badge bg-danger", badge2: "Hot", badgeColor2: "badge-tag badge bg-danger", },
    { id: "Backinstocknotification", lable: "Back in stock notification", link: "/product-detail-back-in-stock-notification" },
    { id: "VariantImagesGrouped", lable: "Variant Images Grouped", link: "/product-detail-variant-images-grouped", badge: "Hot", badgeColor: "badge-tag badge bg-danger", badge2: "Hot", badgeColor2: "badge-tag badge bg-danger", },
    { id: "SizeGuideHTML", lable: "Size Guide HTML", link: "/product-detail-layout-01" },
    { id: "Delivery&Return", lable: "Delivery & Return", link: "/product-detail-layout-01" },
    { id: "AskaQuestion", lable: "Ask a Question", link: "/product-detail-layout-01" },
    { id: "Productsticky", lable: "Product sticky", link: "/product-detail-product-sticky" },
    { id: "360°product viewer", lable: "360° product viewer", link: "/product-detail-360-viewer" },
    { id: "Dynamiccheckoutbuttons", lable: "Dynamic checkout buttons", link: "/product-detail-swatch-radio", badge: "Hot", badgeColor: "badge-tag badge bg-danger", badgeStyle: { "whiteSpace": "nowrap" }, badge2: "Hot", badgeColor2: "badge-tag badge bg-danger", },
    { id: "Stickyaddtocart", lable: "Sticky add to cart", link: "/product-detail-layout-01", badge: "Hot", badgeColor: "badge-tag badge bg-danger", badge2: "Hot", badgeColor2: "badge-tag badge bg-danger", },

]
export {ProductLayout,ProductDetail,ProductSwatch,ProductFeatures}